# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Suvi's House
description: > # this means to ignore newlines until "baseurl:"
  This site is a little about me, Suvethan Vignarajah (Suvi), and my interests.
  I'll be blogging about web technologies (maybe mostly front-end), and some
  random fun stuff as well - just for kicks. Have a look around, your comments
  and feedback are most certainly welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svignara.github.io" # the base hostname & protocol for your site
twitter_username: suvi_v
github_username: svignara
permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json]

# Collections
collections:
  category_pages:
    output: true
    permalink: /:path/